# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
excerpt_separator: <!--more-->

plugins:
  - jekyll-paginate
  - jekyll-analytics
  - jekyll-redirect-from
  - jekyll-tagging-related_posts

exclude: [vendor]

# Setup
title:               Thoughts
tagline:             '@skryl.org'
description:         'Ideas I remembered to scribble down'
url:                 http://thoughts.skryl.org
repository:          'skryl/thoughts.skryl.org'
baseurl:             ''
paginate:            5
host:                localhost
port:                4000

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed


# About/contact
author:
  name:              Alex Skryl
  url:               https://twitter.com/skryl
  email:             aleksey.skryl@gmail.com
  github:            https://github.com/skryl
  homepage:          https://skryl.org
  contact:
    github:    https://github.com/skryl
    twitter:   https://twitter.com/_skryl_
    linkedin:  https://www.linkedin.com/in/skryl

staticman:
  api:    'staticman3.herokuapp.com'
  branch: 'master'

recaptcha:
  sitekey: '6LfjXXUUAAAAADC7c2jCRMxBwa5u1pAs-PISea6V'
  secret: '6LfjXXUUAAAAACqGXg0jgXSkUVOVRToccdf3G0KS'

# Tracking
jekyll_analytics:
  GoogleAnalytics:
    id: UA-29940604-1